;; Run from repository root with: sbcl --script agent-tools/test_text.lisp
(load "slurp.lisp")
(in-package :slurp)
(defvar *checks* 0)
(defun check (value)
  (incf *checks*)
  (unless value (error "Check ~D failed" *checks*)))
(defun rejects (thunk)
  (check (handler-case (progn (funcall thunk) nil) (error () t))))
(let* ((rom (read-rom "slime_original.gba"))
       (table (load-translation-table "SlimeDialog.tbl"))
       (small (load-translation-table "Slime_Small.tbl"))
       (enc (invert-alist (reverse table)))
       (enc-small (invert-alist (reverse small))))
  (load-font-metrics rom)
  (check (= (glyph-width #x11) 4))
  (check (= (glyph-width #x1d) 6))
  (check (= (glyph-width #x10b) 11))
  (check (equal (reflow-string '(52 "A A") :width 26) '(52 "A A")))
  (check (equal (reflow-string '(52 "A A") :width 25) '(52 "A" (newline) "A")))
  (check (equal (reflow-string '(52 "A " (color 2) "A" (color 0) "!") :width 26)
                '(52 "A" (newline) (color 2) "A" (color 0) "!")))
  (check (equal (reflow-string '(52 "a" (color 2) "b" (color 0) " c!"))
                '(52 "a" (color 2) "b" (color 0) " c!")))
  (check (equal (reflow-string '(52 "A" (show-prompt) (wait-input) (newline) "B" (wait-input)))
                '(52 "A" (show-prompt) (wait-input) (newline) "B" (wait-input))))
  (check (equal (reflow-string '(52 "A A A" (yes-no)) :width 9 :paginate t)
                '(52 "A" (newline) "A" (page) (clear) "A" (yes-no))))
  (check (equal (reflow-string '(52 "A A A" (cue) "B") :width 9 :paginate t :ending 1)
                '(52 "A" (newline) "A" (page) (clear) "A" (show-prompt) (wait-input)
                  (clear) "B" (show-prompt) (wait-input))))
  ;; Manual mode retains authored waits/scrolling and the legacy overflow fallback.
  (check (equal (reflow-string '(52 "A A A") :width 9 :paginate t :manual-breaks t)
                '(52 "A" (newline) "A" (show-prompt) (wait-input) (newline) "A")))
  (check (equal (reflow-string '(52 "A" (show-prompt) (wait-input)
                                  (force-newline) "B") :paginate t :manual-breaks t)
                '(52 "A" (show-prompt) (wait-input) (newline) "B")))
  (check (equal (reflow-string '(52 "A" (switch-window) (name "B") "B")
                               :paginate t :manual-breaks t)
                '(52 "A" (switch-window) (name "B") "B")))
  ;; A speaker name or choice does not grant pagination permission.
  (rejects (lambda () (reflow-string '(52 (name "A") "A A A") :width 9)))
  (rejects (lambda () (reflow-string '(52 "A A A" (yes-no)) :width 9)))
  (check (equal (reflow-string '(55 "A A A") :width 9 :lines-per-page 3 :paginate nil)
                '(55 "A" (newline) "A" (newline) "A")))
  ;; Showing an indicator alone does not acknowledge a page or reset line count.
  (rejects (lambda () (reflow-string '(52 "A" (force-newline) "B"
                                            (show-prompt) (force-newline) "C") :paginate nil)))
  (check (equal (reflow-string '(60 "Waiting...")) '(60 "Waiting...")))
  (check (equal (reflow-string '(52 "A" (force-newline) "B")) '(52 "A" (newline) "B")))
  (check (equal (reflow-string '(52 "A " (player-name) "!")) '(52 "A " (player-name) "!")))
  (check (equal (reflow-string '(52 "A " (dynamic-text 0) " B")) '(52 "A " (dynamic-text 0) " B")))
  (rejects (lambda () (reflow-string '(52 "WW") :width 10)))
  (rejects (lambda () (reflow-string '(55 "A A A") :width 9)))
  (rejects (lambda () (encode-string enc enc-small '("é"))))
  (rejects (lambda () (encode-string enc enc-small '((byte 13)))))
  (rejects (lambda () (encode-string enc enc-small '((oops)))))
  (check (equal (encode-string enc enc-small '("W<Note><Heart><Copyright>" (dynamic-text 0)))
                '(267 206 230 422 13 0)))
  (let ((decoded (decode-string table small (rom-text-offset rom 1522) rom)))
    (check (member '(dynamic-text 0) decoded :test #'equal))
    (check (equal (last decoded 2) '((show-prompt) (wait-input)))))
  (rejects (lambda () (rom-text-offset rom 1876)))
  (rejects (lambda () (validate-dialogue-entries rom '((1883 "Credits")))))
  (rejects (lambda () (validate-dialogue-entries rom '((1325 "Missing argument" (byte 10))))))
  (rejects (lambda () (validate-dialogue-entries rom '((52 "A" (wait-input) "B")))))
  (rejects (lambda () (validate-dialogue-entries rom '((52 "A" (wait-for-a) "B")))))
  (validate-dialogue-entries rom '((1325 "Edited menu text") (1522 (dynamic-text 0))
                                  (52 "A" (wait-for-a) (force-newline) "B")))
  (check (equal (reflow-string '(52 "A" (wait-input) (force-newline) "B"))
                '(52 "A" (wait-input) (newline) "B")))
  ;; Exercise expansion, actual pointer writes, and multibyte encoding.
  (let ((tiny (make-array (length rom) :element-type '(unsigned-byte 8)
                         :initial-contents rom :adjustable t :fill-pointer (length rom))))
    (patch-text tiny enc enc-small '((52 "W<Heart>" (dynamic-text 0) "A")))
    (check (= (rom-text-offset tiny 52) (length rom)))
    (check (equalp (subseq tiny (length rom)) #(#x01 #x0b #xe6 #x0d 0 #x8c 0))))
  ;; Every decodable ordinary dialogue entry re-encodes to the same tokens.
  ;; GLYPH tokens retain the identity of duplicate table spellings.
  (loop for index from 52 to 2397
        unless (or (<= 1883 index 1901) (member index '(1876 1877 1878 1879 2086)))
        do (let* ((decoded (decode-string table small (rom-text-offset rom index) rom))
                  (codes (encode-string enc enc-small decoded))
                  (bytes (loop for c in codes append (if (> c 255)
                                                        (list (ash c -8) (logand c 255)) (list c))))
                  (again (decode-string table small 0 (append bytes '(0 0)))))
             (check (equal decoded again))
             (check (equalp (coerce (append bytes '(0)) 'vector)
                            (subseq rom (rom-text-offset rom index)
                                    (+ (rom-text-offset rom index) (length bytes) 1)))))))
(format t "~D text-engine checks passed.~%" *checks*)
