;; Internal bridge for build_ips.py. No ROM is read or synthesized here.
(load "slurp.lisp")
(in-package :slurp)
(destructuring-bind (script metrics layouts directory pagination) (uiop:command-line-arguments)
  (let* ((*font-records* (read-all-text-utf metrics))
         (*text-layouts* (read-all-text-utf layouts))
         (*automatic-pages* (string= pagination "automatic"))
         (out (uiop:ensure-directory-pathname directory))
         (encoding (invert-alist (reverse (load-translation-table "SlimeDialog.tbl"))))
         (small (invert-alist (reverse (load-translation-table "Slime_Small.tbl")))))
    (multiple-value-bind (passed failed)
        (prepare-dialogue-preview (read-dialogue-text script))
      (dump-all-text-utf (merge-pathnames "reflowed.txt" out) passed)
      (dump-all-text-utf (merge-pathnames "held.txt" out) failed)
      (let ((records nil))
        (with-open-file (stream (merge-pathnames "payload.bin" out)
                                :direction :output :if-exists :supersede
                                :element-type '(unsigned-byte 8))
          (dolist (entry passed)
            (let ((start (file-position stream)))
              (dolist (code (encode-string encoding small (cdr entry)))
                (when (> code 255) (write-byte (ldb (byte 8 8) code) stream))
                (write-byte (ldb (byte 8 0) code) stream))
              (write-byte 0 stream)
              (push (list (car entry) start (- (file-position stream) start)) records))))
        (dump-all-text-utf (merge-pathnames "records.txt" out) (nreverse records))))))
